source: C:\Users\luqingterity\Desktop\realestate\WEB-INF\classes
topPackageName: com
dest: C:\Users\luqingterity\Desktop\target
fernFlowerPath: C:\Users\luqingterity\Desktop\open-sources\decompile-folder\fernflower.jar